add test for oauth

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -615,6 +615,8 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
+oauth_LIBS
+oauth_CFLAGS
 HAVE_GTK_FALSE
 HAVE_GTK_TRUE
 gtk_LIBS
@@ -758,7 +760,9 @@ PKG_CONFIG
 PKG_CONFIG_PATH
 PKG_CONFIG_LIBDIR
 gtk_CFLAGS
-gtk_LIBS'
+gtk_LIBS
+oauth_CFLAGS
+oauth_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1414,6 +1418,9 @@ Some influential environment variables:
               path overriding pkg-config's built-in search path
   gtk_CFLAGS  C compiler flags for gtk, overriding pkg-config
   gtk_LIBS    linker flags for gtk, overriding pkg-config
+  oauth_CFLAGS
+              C compiler flags for oauth, overriding pkg-config
+  oauth_LIBS  linker flags for oauth, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -11363,6 +11370,78 @@ else
   HAVE_GTK_FALSE=
 fi
 
+
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for oauth" >&5
+$as_echo_n "checking for oauth... " >&6; }
+
+if test -n "$oauth_CFLAGS"; then
+    pkg_cv_oauth_CFLAGS="$oauth_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"\"oauth\"\""; } >&5
+  ($PKG_CONFIG --exists --print-errors ""oauth"") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_oauth_CFLAGS=`$PKG_CONFIG --cflags ""oauth"" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$oauth_LIBS"; then
+    pkg_cv_oauth_LIBS="$oauth_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"\"oauth\"\""; } >&5
+  ($PKG_CONFIG --exists --print-errors ""oauth"") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_oauth_LIBS=`$PKG_CONFIG --libs ""oauth"" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        oauth_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs ""oauth"" 2>&1`
+        else
+	        oauth_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs ""oauth"" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$oauth_PKG_ERRORS" >&5
+
+	have_oauth=no
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	have_oauth=no
+else
+	oauth_CFLAGS=$pkg_cv_oauth_CFLAGS
+	oauth_LIBS=$pkg_cv_oauth_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_oauth=yes
+fi
 
 
 
